#include "./processor_type.hpp"
#include "./processor_base.hpp" 
#include "./processor_context.hpp"
#include "./processor_instance.hpp"
#include "./pipeline_context.hpp"
#include "./pipeline.hpp"
#include "./pipeline_signal.hpp"
